DROP DATABASE ht25_1_1dl301_group_74;
CREATE DATABASE ht25_1_1dl301_group_74;
USE ht25_1_1dl301_group_74;

-- DEPARTMENT
CREATE TABLE Department(
	DepartmentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    ShortDescription VARCHAR(255),
    Description TEXT,
    ParentDepartmentID INT UNSIGNED,
	FOREIGN KEY(ParentDepartmentID) REFERENCES Department(DepartmentID)
		ON DELETE SET NULL	# child department upgrading to parent department 
        ON UPDATE CASCADE	
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- PRODUCT
CREATE TABLE Product(
	ProductID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    ShortDescription VARCHAR(255),
    Description TEXT,
    StockQuantity INT NOT NULL DEFAULT 0,
    BasePriceNet DECIMAL(10 ,2) NOT NULL,
    VATPercent DECIMAL(5, 2) NOT NULL,
    DiscountPercent DECIMAL(5, 2) NOT NULL DEFAULT 0,
    IsFeatured BOOLEAN NOT NULL DEFAULT FALSE,
    DepartmentID INT UNSIGNED NOT NULL,
    FOREIGN KEY(DepartmentID) REFERENCES DEPARTMENT(DepartmentID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- KEYWORD
CREATE TABLE Keyword(
	KeywordID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    KeywordText VARCHAR(100) NOT NULL UNIQUE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- USERS
CREATE TABLE Users(
	UserID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Phone VARCHAR(20) UNIQUE NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Personnummer CHAR(13) UNIQUE NOT NULL,
    UserName VARCHAR(100) NOT NULL,
	UserPassword VARCHAR(255) NOT NULL,
    NewsletterPermission BOOLEAN NOT NULL DEFAULT FALSE,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    PostalCode VARCHAR(10) NOT NULL
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- ORDERS
CREATE TABLE Orders(
	OrderID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OrderStatus ENUM('new','open','dispatched') NOT NULL,
    LastChangeDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP 
						ON UPDATE CURRENT_TIMESTAMP,
    PaymentReference VARCHAR(64) NOT NULL,
    TrackingNumber VARCHAR(100) NOT NULL,
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    PostalCode VARCHAR(10) NOT NULL,
    UserID INT UNSIGNED NOT NULL,
    FOREIGN KEY(UserID)  REFERENCES Users(UserID)
		ON DELETE RESTRICT
        ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- PRODUCT_KEYWORD
CREATE TABLE Product_Keyword(
	ProductID INT UNSIGNED NOT NULL,
    KeywordID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ProductID, KeywordID),
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
		ON DELETE CASCADE
        ON UPDATE CASCADE,
	FOREIGN KEY(KeywordID) REFERENCES Keyword(KeywordID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- USER_PRODUCT
CREATE TABLE User_Product(
	ProductID INT UNSIGNED NOT NULL,
    UserID INT UNSIGNED NOT NULL,
    Stars TINYINT UNSIGNED NOT NULL CHECK (Stars BETWEEN 1 AND 5),
    ReviewText TEXT,
    ReviewDateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ProductID, UserID),
	FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
		ON DELETE CASCADE 
        ON UPDATE CASCADE,
	FOREIGN KEY(UserID) REFERENCES Users(UserID)
		 ON DELETE CASCADE 
         ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;

-- ORDER PRODUCT
CREATE TABLE Order_Product(
	ProductID INT UNSIGNED NOT NULL,
    OrderID INT UNSIGNED NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    DiscountPercentAtOrderTime DECIMAL(5, 2) NOT NULL DEFAULT 0,
    UnitPriceNetAtOrderTime DECIMAL(10, 2) NOT NULL,
    VATPercentAtOrderTime DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (OrderID, ProductID),
    FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)
		 ON DELETE CASCADE 
         ON UPDATE CASCADE,
    FOREIGN KEY(ProductID) REFERENCES Product(ProductID)
		ON DELETE RESTRICT 
        ON UPDATE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8MB4;






















